name: Generate profile cards

on:
  workflow_dispatch:
  schedule:
    - cron: "23 2 * * *"
  push:
    paths:
      - ".github/workflows/profile-cards.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Gr1xzz11
          BRANCH_NAME: main
          UTC_OFFSET: 7
          AUTO_PUSH: true
